export const audiobooks = [
  {
    id: "LaMetamorfosis01",
    title: "La Metamorfosis",
    author: "Franz Kafka",
    genre: "Novela Corta",
    year: 1915,
    description: "Una obra maestra del escritor checo Franz Kafka.",
    prologue: "La Metamorfosis es una novela corta escrita por el autor checo Franz Kafka. La historia comienza de manera abrupta con el protagonista, Gregor Samsa, despertándose una mañana para descubrir que se ha transformado en un enorme insecto, a menudo descrito como una cucaracha gigante. Este evento inexplicable es el punto de partida para una exploración profunda de temas como la alienación, la identidad, y la condición humana. Gregor Samsa, antes de su transformación, es un comerciante viajero que trabaja arduamente para mantener a su familia.Su transformación impacta drásticamente la dinámica familiar.Incapaz de comunicarse con los demás y convertido en una carga, Gregor se ve confinado a su habitación, enfrentándose al rechazo y a la incomprensión de su familia.Su hermana, Grete, al principio intenta cuidar de él, pero con el tiempo, también se aleja, y la familia busca deshacerse de él.",
    coverUrl: "../Covers1x1-1000px/laMetamorfosis-1x1.jpg",
    audioUrl: "./audio/books/La metamorfosis - Capítulo 1.mp3",
    pdfUrl: "./Ebooks/La Metamorfosis - Franz Kfka.pdf",
    media: ["IoHeadset", "FaGlasses"],
    //   { name: "IoHeadset", key: "1" },
    //   { name: "FaGlasses", key: "2" }
    // ],
    categoryId: "Ficción",
  },
  {
    id: "ElPrincipito01",
    title: "El Principito",
    author: "Antoine de Saint-Exupéry",
    genre: "Fábula",
    year: 1943,
    description: "El Principito” es una narración corta del escritor francés Antoine de Saint-Exupéry.",
    prologue: "La obra poética escrita en prosa tiene una forma armónica, que surge de su inagotable y profunda poesía, de los sentimientos, del amor a la vida, a la naturaleza y al hombre...",
    coverUrl: "./Covers1x1-1000px/elPrincipito-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: ["IoHeadset"],
    categoryId: "Ficción",
  },
  {
    id: "AnaKarenina01",
    title: "Ana Karenina",
    author: "Lev Tolstói",
    genre: "Novela",
    year: 1873,
    description: "Ana Karénina es una novela publicada por primera vez en forma de libro en 1878. Considerada una de las obras literarias más grandes jamás escritas",
    prologue: "En una sociedad rusa dominada por la nobleza y las rígidas convenciones sociales del siglo XIX, Ana Karenina de León Tolstói emerge como una poderosa exploración del amor, la infidelidad y las consecuencias de las pasiones humanas.",
    coverUrl: "./Covers1x1-1000px/anaKarenina-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: [],
    categoryId: "Drama",
  },
  {
    id: "Mujercitas01",
    title: "Mujercitas",
    author: "Louisa May Alcott",
    genre: "Novela",
    year: 1868,
    description: "Ana Karénina es una novela publicada por primera vez en forma de libro en 1878. Considerada una de las obras literarias más grandes jamás escritas",
    prologue: "En una sociedad rusa dominada por la nobleza y las rígidas convenciones sociales del siglo XIX, Ana Karenina de León Tolstói emerge como una poderosa exploración del amor, la infidelidad y las consecuencias de las pasiones humanas.",
    coverUrl: "./Covers1x1-1000px/mujercitas-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: [],
    categoryId: "Drama",
  },
  {
    id: "Dracula01",
    title: "Drácula",
    author: "Bram´s Tocker",
    genre: "Novela",
    year: 1868,
    description: "Ana Karénina es una novela publicada por primera vez en forma de libro en 1878. Considerada una de las obras literarias más grandes jamás escritas",
    prologue: "En una sociedad rusa dominada por la nobleza y las rígidas convenciones sociales del siglo XIX, Ana Karenina de León Tolstói emerge como una poderosa exploración del amor, la infidelidad y las consecuencias de las pasiones humanas.",
    coverUrl: "./Covers1x1-1000px/dracula-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: [],
    categoryId: "Drama",
  },
  {
    id: "ElCondeDeMonteCristo01",
    title: "El Conde De Monte Cristo",
    author: "Louisa May Alcott",
    genre: "Novela",
    year: 1868,
    description: "Ana Karénina es una novela publicada por primera vez en forma de libro en 1878. Considerada una de las obras literarias más grandes jamás escritas",
    prologue: "En una sociedad rusa dominada por la nobleza y las rígidas convenciones sociales del siglo XIX, Ana Karenina de León Tolstói emerge como una poderosa exploración del amor, la infidelidad y las consecuencias de las pasiones humanas.",
    coverUrl: "./Covers1x1-1000px/elCondeDeMonteCristo-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: [],
    categoryId: "Drama",
  },
  {
    id: "OrgulloyPrejuicio01",
    title: "Orgullo y Prejuicio",
    author: "Jane Austen",
    genre: "Novela",
    year: 1813,
    description: "Ana Karénina es una novela publicada por primera vez en forma de libro en 1878. Considerada una de las obras literarias más grandes jamás escritas",
    prologue: "En una sociedad rusa dominada por la nobleza y las rígidas convenciones sociales del siglo XIX, Ana Karenina de León Tolstói emerge como una poderosa exploración del amor, la infidelidad y las consecuencias de las pasiones humanas.",
    coverUrl: "./Covers1x1-1000px/orgulloYPrejuicio-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: [],
    categoryId: "Romance",
  },
  {
    id: "MobyDick01",
    title: "Moby Dick",
    author: "Jane Austen",
    genre: "Novela",
    year: 1813,
    description: "Ana Karénina es una novela publicada por primera vez en forma de libro en 1878. Considerada una de las obras literarias más grandes jamás escritas",
    prologue: "En una sociedad rusa dominada por la nobleza y las rígidas convenciones sociales del siglo XIX, Ana Karenina de León Tolstói emerge como una poderosa exploración del amor, la infidelidad y las consecuencias de las pasiones humanas.",
    coverUrl: "./Covers1x1-1000px/mobyDick-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: [],
    categoryId: "Romance",
  },
  {
    id: "MobyDick01",
    title: "Moby Dick",
    author: "Jane Austen",
    genre: "Novela",
    year: 1813,
    description: "Ana Karénina es una novela publicada por primera vez en forma de libro en 1878. Considerada una de las obras literarias más grandes jamás escritas",
    prologue: "En una sociedad rusa dominada por la nobleza y las rígidas convenciones sociales del siglo XIX, Ana Karenina de León Tolstói emerge como una poderosa exploración del amor, la infidelidad y las consecuencias de las pasiones humanas.",
    coverUrl: "./Covers1x1-1000px/mobyDick-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: [],
    categoryId: "Romance",
  },
  {
    id: "MobyDick01",
    title: "Moby Dick",
    author: "Jane Austen",
    genre: "Novela",
    year: 1813,
    description: "Ana Karénina es una novela publicada por primera vez en forma de libro en 1878. Considerada una de las obras literarias más grandes jamás escritas",
    prologue: "En una sociedad rusa dominada por la nobleza y las rígidas convenciones sociales del siglo XIX, Ana Karenina de León Tolstói emerge como una poderosa exploración del amor, la infidelidad y las consecuencias de las pasiones humanas.",
    coverUrl: "./Covers1x1-1000px/mobyDick-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: [],
    categoryId: "Romance",
  },
  {
    id: "MobyDick01",
    title: "Moby Dick",
    author: "Jane Austen",
    genre: "Novela",
    year: 1813,
    description: "Ana Karénina es una novela publicada por primera vez en forma de libro en 1878. Considerada una de las obras literarias más grandes jamás escritas",
    prologue: "En una sociedad rusa dominada por la nobleza y las rígidas convenciones sociales del siglo XIX, Ana Karenina de León Tolstói emerge como una poderosa exploración del amor, la infidelidad y las consecuencias de las pasiones humanas.",
    coverUrl: "./Covers1x1-1000px/mobyDick-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: [],
    categoryId: "Romance",
  },
  {
    id: "MobyDick01",
    title: "Moby Dick",
    author: "Jane Austen",
    genre: "Novela",
    year: 1813,
    description: "Ana Karénina es una novela publicada por primera vez en forma de libro en 1878. Considerada una de las obras literarias más grandes jamás escritas",
    prologue: "En una sociedad rusa dominada por la nobleza y las rígidas convenciones sociales del siglo XIX, Ana Karenina de León Tolstói emerge como una poderosa exploración del amor, la infidelidad y las consecuencias de las pasiones humanas.",
    coverUrl: "./Covers1x1-1000px/mobyDick-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: [],
    categoryId: "Romance",
  },
  {
    id: "MobyDick01",
    title: "Moby Dick",
    author: "Jane Austen",
    genre: "Novela",
    year: 1813,
    description: "Ana Karénina es una novela publicada por primera vez en forma de libro en 1878. Considerada una de las obras literarias más grandes jamás escritas",
    prologue: "En una sociedad rusa dominada por la nobleza y las rígidas convenciones sociales del siglo XIX, Ana Karenina de León Tolstói emerge como una poderosa exploración del amor, la infidelidad y las consecuencias de las pasiones humanas.",
    coverUrl: "./Covers1x1-1000px/mobyDick-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: [],
    categoryId: "Romance",
  },
  {
    id: "MobyDick01",
    title: "Moby Dick",
    author: "Jane Austen",
    genre: "Novela",
    year: 1813,
    description: "Ana Karénina es una novela publicada por primera vez en forma de libro en 1878. Considerada una de las obras literarias más grandes jamás escritas",
    prologue: "En una sociedad rusa dominada por la nobleza y las rígidas convenciones sociales del siglo XIX, Ana Karenina de León Tolstói emerge como una poderosa exploración del amor, la infidelidad y las consecuencias de las pasiones humanas.",
    coverUrl: "./Covers1x1-1000px/mobyDick-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: [],
    categoryId: "Romance",
  },
  {
    id: "MobyDick01",
    title: "Moby Dick",
    author: "Jane Austen",
    genre: "Novela",
    year: 1813,
    description: "Ana Karénina es una novela publicada por primera vez en forma de libro en 1878. Considerada una de las obras literarias más grandes jamás escritas",
    prologue: "En una sociedad rusa dominada por la nobleza y las rígidas convenciones sociales del siglo XIX, Ana Karenina de León Tolstói emerge como una poderosa exploración del amor, la infidelidad y las consecuencias de las pasiones humanas.",
    coverUrl: "./Covers1x1-1000px/mobyDick-1x1.jpg",
    audioUrl: "./audio/books/El Principito - 1.mp3",
    pdfUrl: "",
    media: [],
    categoryId: "Romance",
  },
];

